# Generated by Django 2.2 on 2019-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0004_photolikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20)),
                ('follower', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
