# Generated by Django 2.2 on 2019-04-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0005_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='coords',
            field=models.CharField(max_length=40),
        ),
    ]
