# Generated by Django 2.2 on 2019-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0007_photo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=20),
        ),
    ]
