# Generated by Django 2.2 on 2019-04-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0008_auto_20190415_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
